### ISSUE TITLE
Parsing CSV problematic when contents include commas

### ISSUE THREAD

**Issue by julianharty** [julianharty/app-store-reviews-app#15]
The current parsing fails to distinguish between commas separating values and commas in the value e.g. in a quoted string "this, not that". Here's the current code:

    String[] nextRow() throws IOException {
        String line = reader.readLine();
        return null == line ? null : line.split(",");
    }
I need to implement a more discerning parser. Time to do so about now :)

BTW: it might also be worth adding some robustness checks against the contents being read to detect and cope with malformed CSV files. And finally for this bug/enhancement - make the program robust so it doesn't crash when problems happen (currently the app quits - not what I or the user wants).

**Comment by dakkad** [comment]
There are some good CSV parsers around. Let's review a few.

**Comment by julianharty** [comment]
I agree, OpenCSV seems to be one option, however I didn't want the faff of
adding a large blob of code for what may be a fairly simple challenge, and
this code was just enough to enable me to load the files containing
reviews.

How about we create a mini-test to try out some CSV parsers and compare
their robustness, capabilities and footprint? Then we can replace my basic
code if and when we find one worth the footprint and effort :)

**Comment by julianharty** [comment]
Here's a useful, comprehensive example with tests. https://www.mkyong.com/java/how-to-read-and-parse-csv-file-in-java/

**Comment by julianharty** [comment]
And the official RFC https://tools.ietf.org/html/rfc4180

**Comment by dakkad** [comment]
https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Splitter.html

https://commons.apache.org/proper/commons-csv/
